### ISSUE TITLE
MosaiGo

### ISSUE THREAD

**Issue by Ruyaoo** [HackYardo/VastGo#9]
First of all, I want to express my thanks.

Can MosaicGo be supported in your go rules?

As shown in the figure:
![百度贴吧](https://user-images.githubusercontent.com/102702890/188267536-3479a657-a561-4d1c-bdd3-69dfc626398c.jpg)

**Comment by Ruyaoo** [comment]
![Uploading 百度贴吧.jpg…]()

**Comment by HackYardo** [comment]
There are **two kinds of** fancy Go modes:
  1. the first is to expand the basic rules
  2. the second is to change the basic rules

The core of the basic rules of Go consists of three points: 
  1. the matrix board
  2. the capture rule
  3. the ko rule. 

In MosaiGo, since the board cannot be mapped to a matrix, it belongs to the second, while this project only supports the first.  In fact, it is also beyond the current third-generation Go AI, perhaps the fifth-generation Go AI can play it in twenty years. 

If you only want to play with people, without AI, you'd better print the board out and find someone to play with, or ask some Go server to support this, such as:
- http://www.dashstofsk.net/gorilla.html
- https://online-go.com/
- https://www.gokgs.com/
